//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlertas
    {
        public long CodigoAlerta { get; set; }
        public string DniCli { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public Nullable<int> idTurno { get; set; }
        public string estado { get; set; }
    
        public virtual tbClientes tbClientes { get; set; }
        public virtual tbTurnos tbTurnos { get; set; }
    }
}
