//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAuditoria
    {
        public long id { get; private set; }
        public string DNI_Usuario { get; private set; }
        public string descripcionAccion { get; private set; }
        public Nullable<System.DateTime> fecha { get; private set; }
        public string hora { get; private set; }

        public static tbAuditoria crear(string _dNI_Usuario, string _descripcionAccion, DateTime? _fecha, string _hora) {
            return new tbAuditoria() {
                DNI_Usuario = _dNI_Usuario,
                descripcionAccion = _descripcionAccion,
                fecha = _fecha,
                hora = _hora
            };
        }
    }
}
