//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCompras()
        {
            this.tbDetalleCompras = new HashSet<tbDetalleCompras>();
        }
    
        public string Serie { get; private set; }
        public string Numero { get; private set; }
        public Nullable<System.DateTime> Fecha { get; private set; }
        public string DniEmpleado { get; private set; }
        public string RucProveedor { get; private set; }
        public Nullable<decimal> Total { get; private set; }
        public string Estado { get; private set; }

        public static tbCompras crear(string _serie, string _numero, DateTime? _fecha, string _dniEmpleado, string _rucProveedor, decimal? _total, string _estado) {
            return new tbCompras() {
                Serie = _serie,
                Numero = _numero,
                Fecha = _fecha,
                DniEmpleado = _dniEmpleado,
                RucProveedor = _rucProveedor,
                Total = _total,
                Estado = _estado
            };
        }

        public virtual tbEmpleados tbEmpleados { get; set; }
        public virtual tbProveedores tbProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleCompras> tbDetalleCompras { get; set; }
    }
}
