//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCompras()
        {
            this.tbDetalleCompras = new HashSet<tbDetalleCompras>();
        }
    
        public string Serie { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string DniEmpleado { get; set; }
        public string RucProveedor { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Estado { get; set; }
    
        public virtual tbEmpleados tbEmpleados { get; set; }
        public virtual tbProveedores tbProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleCompras> tbDetalleCompras { get; set; }
    }
}
