//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDetalleCompras
    {
        public long idDetalleComprobante { get; set; }
        public string Serie { get; set; }
        public string Numero { get; set; }
        public string CodigoLote { get; set; }
        public string Descripcion { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Importe { get; set; }
    
        public virtual tbCompras tbCompras { get; set; }
        public virtual tbLotes tbLotes { get; set; }
    }
}
