//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System.Collections.Generic;
    
    public partial class tbEmpleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEmpleados()
        {
            this.tbCompras = new HashSet<tbCompras>();
            this.tbComprobante = new HashSet<tbComprobante>();
        }
    
        public string DniEmpleado { get; private set; }
        public string Nombres { get; private set; }
        public string Apellidos { get; private set; }
        public string Direccion { get; private set; }
        public string Correo { get; private set; }
        public string Telefono { get; private set; }
        public string Codigo_Cargo { get; private set; }
        public int idTurno { get; private set; }
        public string Estado { get; private set; }
        public string Usuario { get; private set; }
        public string Contraseña { get; private set; }

        public static tbEmpleados crear(string _dniEmpleado, string _nombres, string _apellidos, string _direccion, string _correo, string _telefono, string _codigo_Cargo, int _idTurno, string _estado, string _usuario, string _contraseña) {
            return new tbEmpleados() {
                DniEmpleado = _dniEmpleado,
                Nombres = _nombres,
                Apellidos = _apellidos,
                Direccion = _direccion,
                Correo = _correo,
                Telefono = _telefono,
                Codigo_Cargo = _codigo_Cargo,
                idTurno = _idTurno,
                Estado = _estado,
                Usuario = _usuario,
                Contraseña = _contraseña
            };
        }

        public virtual tbCargos tbCargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCompras> tbCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbComprobante> tbComprobante { get; set; }
        public virtual tbTurnos tbTurnos { get; set; }
    }
}
