//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbKardex
    {
        public long idKardex { get; set; }
        public string CodLote { get; set; }
        public string DniEmpleado { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public string Estado { get; set; }
        public string Hora { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }

        public static tbKardex crear(string _codLote, string _dniEmpleado, string _descripcion, int? _cantidad, decimal? _precioUnitario, string _estado, string _hora, DateTime? _fecha) {
            return new tbKardex() {
                CodLote = _codLote,
                DniEmpleado = _dniEmpleado,
                Descripcion = _descripcion,
                Cantidad = _cantidad,
                PrecioUnitario = _precioUnitario,
                Estado = _estado,
                Hora = _hora,
                Fecha = _fecha
            };
        }
    }
}
