//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocios.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Negocios.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AC76ca801c98415e33077d54efdc84a452.
        /// </summary>
        internal static string accountSid {
            get {
                return ResourceManager.GetString("accountSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1a7ab12a65c2fbdc79af030505d78158.
        /// </summary>
        internal static string authToken {
            get {
                return ResourceManager.GetString("authToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pruebaprogra2@gmail.com.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://dniruc.apisperu.com/api/v1/dni/.
        /// </summary>
        internal static string linkReniecDNI {
            get {
                return ResourceManager.GetString("linkReniecDNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://dniruc.apisperu.com/api/v1/ruc/.
        /// </summary>
        internal static string linkReniecRUC {
            get {
                return ResourceManager.GetString("linkReniecRUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://76524e8f3cfa.ngrok.io/.
        /// </summary>
        internal static string linkSocket {
            get {
                return ResourceManager.GetString("linkSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mongodb+srv://mean_user:C2lJICERLuPwsisG@cluster0.gx6au.mongodb.net/dbjeanet?retryWrites=true&amp;w=majority.
        /// </summary>
        internal static string mongoKey {
            get {
                return ResourceManager.GetString("mongoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistemas.123.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InByb21vMjAxNjc0QGdtYWlsLmNvbSJ9.SDxqQGi2nMScGlxP_EP6TXOo-mwksYzZgA4y-GvB5oc.
        /// </summary>
        internal static string reniecApiToken {
            get {
                return ResourceManager.GetString("reniecApiToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a +14232056903.
        /// </summary>
        internal static string twilioPhone {
            get {
                return ResourceManager.GetString("twilioPhone", resourceCulture);
            }
        }
    }
}
